[package]
name = "stm32l4kc-hal"
version = "0.1.0"
authors = ["Scott <MabezDev@gmail.com>"]

[dependencies]
cortex-m = "0.5.2"
nb = "0.1.1"
cast = "0.2.2"

[dependencies.embedded-hal]
version = "0.2.1"
features = ["unproven"]

[dependencies.stm32l4]
version = "0.2.1"
features = ["stm32l4x2", "rt"]