[package]
name = "stm32l432xx-hal"
version = "0.2.4"
authors = ["Scott Mabin <MabezDev@gmail.com>"]
description = "Hardware abstraction layer for the stm32l432xx chips"
keywords = ["no-std", "stm32l432xx", "stm32l432kc", "embedded", "embedded-hal"]
repository = "https://github.com/MabezDev/stm32l432xx-hal"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = [
	".travis.yml",
	".gitignore",
	"docs/",
	"docs/*"
]

[dependencies]
cortex-m = "0.5.7"
nb = "0.1.1"

[dependencies.cast]
version  = "0.2.2"
default-features = false

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.embedded-hal]
version = "0.2.1"
features = ["unproven"]

[dependencies.stm32l4]
version = "0.3.2"
features = ["stm32l4x2", "rt"]

[dev-dependencies]
panic-semihosting = "0.5.0"
cortex-m-semihosting = "0.3.1"
cortex-m-rt = "0.6.5"

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true