[package]
name = "stm32l432xx-hal"
version = "0.1.0"
authors = ["Scott <MabezDev@gmail.com>"]

[dependencies]
cortex-m = "0.5.2"
nb = "0.1.1"
cortex-m-rt = "0.5.1"

[dependencies.cast]
version  = "0.2.2"
default-features = false

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.embedded-hal]
version = "0.2.1"
features = ["unproven"]

[dependencies.stm32l4]
version = "0.2.1"
features = ["stm32l4x2", "rt"]

[dev-dependencies]
panic-semihosting = "0.3.0"
cortex-m-semihosting = "0.3.0"